raw_data_processing:
  colums_not_to_keep:
  - brand_id
  - product_id

execute_notebook:
  data_path: data/processed/reviews.csv

split:
  test_size: 0.2
  stratify: true

clean:
  missing_threshold: 0.5
  text_col:
  - review_text
  - review_title

validate:
  cv: 3

train:
  model: most_frequent

